my_project/my_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


urlpatterns = [
    path('', lambda _ : redirect('recipe/')),
    path('admin/', admin.site.urls),
    path('recipe/', include('recipeapp.urls')),
    path("user/", include('userapp.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

my_project/recipeapp/urls.py
from django.urls import path
from .views import rec_index, rec_create, rec_view, rec_update, rec_search, rec_search2

app_name = "recipeapp"

urlpatterns = [
    path("", rec_index, name="index"),
    path("create/", rec_create, name="create"),
    path("update/<int:pk>", rec_update, name="update"),
    path("<int:_pk>", rec_view, name="recipe"),
    path("search/<str:name>", rec_search, name="search"),
    path("search2/", rec_search2, name="search2")
]

my_project/userapp/urls.py
from django.shortcuts import redirect
from django.urls import path
from .views import profile_view, user_view
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from .views import register


app_name = "userapp"


def my_logout(request):
    logout(request)
    return redirect("/")

urlpatterns = [
    path("profile/", profile_view, name="profile"),
    path("login/", LoginView.as_view(template_name="userapp/login.html", redirect_authenticated_user=True), name="login"),
    path("logout/", my_logout, name="logout"),
    path("register/", register, name="register"),
    path("<str:name>/", user_view, name="user")
]

my_project/recipeapp/models.py
from django.db import models
from django.contrib.auth.models import User

CF_LEN_MAX = 20

def rec_path(rec, filename):
    return f"img/{rec.pk}/{filename}"

# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=CF_LEN_MAX)
    desc = models.TextField(null=False, blank=True)
    alg = models.TextField(null=False, blank=True)
    time = models.IntegerField(null=False, default=1)
    img = models.ImageField(null=True, blank=True, upload_to=rec_path)
    auth = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    
class Cat(models.Model):
    name = models.CharField(max_length=CF_LEN_MAX)
    recs = models.ManyToManyField(Recipe, related_name="category")

my_project/userapp/models.py
from django.db import models

# Create your models here.

my_project/recipeapp/forms.py
from django import forms
from .models import CF_LEN_MAX, Recipe

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = "name", "desc", "alg", "time", "img"



# class RecipeForm(forms.Form):
#     name = forms.CharField(label="Name ", max_length=CF_LEN_MAX)
#     desc = forms.CharField(label="Description ", widget=forms.Textarea)
#     alg = forms.CharField(label="Algorithm ", widget=forms.Textarea)
#     time = forms.IntegerField(label="Cooking time ", min_value=1, max_value=69, initial=1)

my_project/recipeapp/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Recipe
from .forms import RecipeForm

# Create your views here.
def rec_index(request):
    context = {
        "recs" : Recipe.objects.order_by('?')
        # "recs" : Recipe.objects.all()
    }

    return render(request, "recipeapp/index.html", context)

def rec_search(request, name):
    return render(request, "recipeapp/index.html", { "recs" : Recipe.objects.filter(name__contains=name)})

def rec_search2(request):
    string = request.GET.get("search_bar")
    # print(string, type(string))

    return rec_search(request, string)

@login_required(login_url="userapp:login")
def rec_create(request):

    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES)

        form.instance.auth = request.user
        if form.is_valid():
            form.save()

            url = reverse("recipeapp:index")
            return redirect(url)
    
    form = RecipeForm()
    context = {
        "form" : form
    }

    return render(request, "recipeapp/create.html", context=context)

@login_required(login_url="userapp:login")
def rec_update(request, pk):
    inst = get_object_or_404(Recipe, id=pk)

    if inst.auth != request.user:
        return rec_view(request, pk)
    
    form = RecipeForm(request.POST or None, instance=inst)

    if form.is_valid():
        form.save()

        return redirect(reverse("recipeapp:index"))
    
    return render(request, "recipeapp/create.html", {"form" : form})

from django.contrib import messages

def rec_view(request, _pk):
    rec = get_object_or_404(Recipe, pk=_pk)

    messages.debug(request, f"Obj : {rec.name} {rec.auth} {rec.img}")
    print("dbg", type(rec.img))

    return render(request, "recipeapp/recipe.html", {"rec" : rec})

my_project/userapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your views here.
def profile_view(request):
    return render(request, "userapp/profile.html", {"user" : request.user})

def user_view(request, name):
    if name == request.user.username:
        return profile_view(request)
    
    print(name, request.user.username)
    user = get_object_or_404(User, username=name)
    
    return render(request, "userapp/user.html", { "user" : user })

def register(request):
    if request.method  == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = UserCreationForm()

    return render(request, 'userapp/register.html', {"form" : form})

# class UserRegisterView(CreateView):
#     form_class = UserCreationForm
#     template_name = "userapp/register.html"
#     success_url = reverse_lazy("userapp:profile")

my_project/my_project/templates/my_project/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
</head>
<body>
    {% load static %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
     <img src="{% static 'default.jpg' %}" alt="Pepper" style="height: 60px; object-fit: contain; margin-right: 5px;">
    <a class="navbar-brand" href="/">Recipe book</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'userapp:profile' %}">My profile</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userapp:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userapp:login' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userapp:register' %}">Register</a>
        </li>
        </li>
        {% endif %}
        </ul>
      <form class="d-flex" role="search" method="GET" action="{% url 'recipeapp:search2' %}">

        {% csrf_token %}
        <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="search_bar"/>
        <button class="btn btn-outline-success" type="submit"">Search</button>
      </form>
    </div>
  </div>
    </nav>

    {% if messages %}
        {% for m in messages %}
            <div class="alert alert-{{ m.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}

    {% endblock %}
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</body>
</html>

my_project/recipeapp/templates/recipeapp/create.html
{% extends "my_project/base.html" %}

{% block title %}
    New recipe
{% endblock %}

{% block body %}

<div class="mb-3 container">
    <h1>
        New recipe
    </h1>
</div>
<div class ="mb-3 container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">
            Submit
        </button>
    </form>
</div>
<div class="container mb-3">
    <a class="btn btn-primary" href="{% url 'recipeapp:index' %}">
        Back
    </a>
</div>

{% endblock %}

my_project/recipeapp/templates/recipeapp/index.html
{% extends "my_project/base.html" %}


{% block body %}
<div class="container mb-3">
    <h1> Recipe book </h1>
    <hr>
    <div class="container mb-3">
        <ul>
            {% for r in recs|slice:":5" %}
            <li>
                 <p><a href="{% url 'recipeapp:recipe' _pk=r.pk %}">
                    {{ r.name }}
                 </a></p>
                <p>{{ r.desc }}</p>
                <p>Author : {{ r.auth }}</p>
            </li>
            <hr>
            {% endfor %}
        </ul>
    </div>
    <div class="container mb-3">
        <a class="btn btn-primary" href="{% url 'recipeapp:create' %}">
            Create a new recipe
        </a>
    </div>
</div>
{% endblock %}

my_project/recipeapp/templates/recipeapp/recipe.html
{% extends "my_project/base.html" %}

{% block title %}
    Some recipe
{% endblock %}

{% block body %}
    <div class="container mb-3">
        <h1> {{rec.name}} </h1>
        <hr>
    </div>
    <div class="container mb-3">
        <p>Description</p>
        {{ rec.desc }}
        <hr>
    </div>
    <div class="container mb-3">
        <p>Algorithm</p>
        {{ rec.alg }}
        <hr>
    </div>
    <div class="container mb-3">
        <p>Author</p>
        {% if rec.auth %}
        <a href="{% url 'userapp:user' name=rec.auth.username %}">{{rec.auth.username}}</a>
        {% else %}
        <p>Anonymous</p>
        {% endif %}
        <hr>
    </div>
    {% if rec.img %}
    <div class="container mb-3">
        <img src="{{ rec.img.url }}">
        <hr>
    </div>
    {% endif %}
    {% if rec.auth == request.user %}
    <div class="container mb-3">
        <a class="btn btn-primary" href="{% url 'recipeapp:update' pk=rec.pk %}">Update</a>
        <hr>
    </div>
    {% endif %}
    <div class="container mb-3">
        <a class="btn btn-primary" href="{% url 'recipeapp:index' %}">
            Back
        </a>
        <hr>
    </div>
{% endblock %}

my_project/recipeapp/templates/recipeapp/user.html
<!-- {% extends "my_project/base.html" %}

{% block title %}
    User info
{% endblock %}

{% block body %}
    <h1>
        User info
    </h1>

    {% if user.is_authenticated %}
    <p>
        Username : {{ user.username }}
    </p>
    {% else %}
    <p>
        Anonynous user
    </p>
    {% endif %}
{% endblock %} -->

my_project/userapp/templates/userapp/login.html
{% extends "my_project/base.html" %}

{% block title %}
    Login
{% endblock %}

{% block body %}
<div class="container mb-3">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}

        <button class="btn btn-primary" type="submit">Login</button>
    </form>
</div>
{% endblock %}

my_project/userapp/templates/userapp/profile.html
{% extends "my_project/base.html" %}

{% block title %}
    My profile
{% endblock %}

{% block body %}
    <div class="container mb-3">
        <h1>
            My profile
        </h1>

    </div>

    <div class="container mb-3">
        {% if user.is_authenticated %}
        <p>
            Username : {{ user.username }}
        </p>
        {% else %}
        <p>
            Anonynous user
        </p>
        {% endif %}
    </div>
{% endblock %}

my_project/userapp/templates/userapp/register.html
{% extends "my_project/base.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <div class="container mb-3">
        <h1>
            Register
        </h1>
    </div>
    <div class="container mb-3">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">
            Create
        </button>
    </form>
    </div>
{% endblock %}

my_project/userapp/templates/userapp/user.html
{% extends "my_project/base.html" %}

{% block title %}
    User info
{% endblock %}

{% block body %}
    <div class="container mb-3">
        <h2>
            User info
        </h2>
        <p>Name : {{ user.username }}</p>
    </div>
{% endblock %}